const err = new Error('test')
throw err